name: Deploy on Push to Main

# Déclencheur pour les événements "push" sur la branche "main"
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérification du code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Exécuter les tests
      - name: Run tests
        run: npm test

      # Étape 3 : Configurer l'accès SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Étape 4 : Exécuter le pull sur Le serveurs
      - name: Pull latest changes on the server
        run: |
          ssh raphyserver@${{ secrets.SSH_HOST }} <<EOF
            cd ${{ secrets.WORK_DIR }}
            git checkout main
            git pull
          EOF
      # Étape 5 : Construire l'image Dockers
      - name: Build Docker image
        run: |
          ssh raphyserver@${{ secrets.SSH_HOST }} <<EOF
           cd ${{ secrets.WORK_DIR }}/client
           docker-compose -f docker-compose.yml
           docker system prune -af
           docker image prune -af
           docker-compose up -d --build
          EOF