name: Deploy on Push to Main

# Déclencheur pour les événements "push" sur la branche "main"
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérification du code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer l'accès SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 3.89.252.255 >> ~/.ssh/known_hosts

      # Étape 3 : Exécuter le pull sur Le serveurs
      - name: Pull latest changes on the server
        run: |
          ssh raphyserver@3.89.252.255 <<EOF
            cd /home/raphyserver/www/AARON
            git checkout main
            git pull
          EOF
      # Étape 4 : Construire l'image Dockers
      - name: Build Docker image
        run: |
          ssh raphyserver@3.89.252.255 <<EOF
           cd /home/raphyserver/www/AARON/client
           docker build -t react-app:latest .
           docker-compose up -d
          EOF